name: Notion Period Automation (Daily + Dispatch)

on:
  schedule:
    # JST 00:00 = UTC 15:00
    - cron: "0 15 * * *"
  repository_dispatch:
    types: [notion-update]
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Run
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          LUTEAL_DAYS: ${{ vars.LUTEAL_DAYS }}
          DEFAULT_CYCLE: 28
          CREATE_PLAN_PAGES: ${{ vars.CREATE_PLAN_PAGES }}
          EVENT_REASON: ${{ github.event.client_payload.reason }}
          MIN_TRIGGER_INTERVAL_SEC: ${{ vars.MIN_TRIGGER_INTERVAL_SEC }}
          STRICT_TEMPLATES: ${{ vars.STRICT_TEMPLATES }}
          MORNING_END_HOUR: ${{ vars.MORNING_END_HOUR }}
          AFTERNOON_END_HOUR: ${{ vars.AFTERNOON_END_HOUR }}
        run: node index.js
